---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

services:
  - docker

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-3.8
    - EMBER_TRY_SCENARIO=ember-lts-3.12
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default-with-jquery
    - EMBER_TRY_SCENARIO=ember-classic

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
  # The below jobs just seem redundant to me, given the above 
  # include:
  #   # runs linting and tests with current locked deps
  #   - stage: "Tests"
  #     name: "Tests"
  #     script:
  #       - npm test
  #   - stage: "Additional Tests"
  #     name: "Floating Dependencies"
  #     install:
  #       - npm install --no-package-lock
  #     script:
  #       - npm test

before_install:
  - npm config set spin false

before_script:
  - docker-compose pull
  - docker-compose up -d
  - bash .wait.sh

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
