---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

services:
  - docker

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

install:
  - npm install

before_script:
  - docker-compose pull
  - docker-compose up -d
  - bash .wait.sh
  
script:
  - ember test
