version: '2'

services:

  fcrepo:
    image: oapass/fcrepo:4.7.5-2.2-SNAPSHOT-8@sha256:75abb2ccc05040f65c4ca854871d7005ea6853c974d70d932823a6ad3b611d23
    container_name: fcrepo
    env_file: .env
    environment:
      - FCREPO_JMS_BASEURL=http://localhost:8080/fcrepo/rest
    ports: 
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_JMS_PORT}:${FCREPO_JMS_PORT}"
      - "${FCREPO_STOMP_PORT}:${FCREPO_STOMP_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    volumes:
      - ./tests/dummy/public/farm.jsonld:/usr/local/tomcat/lib/farm.jsonld:Z

  indexer:
    image: oapass/indexer:0.0.12-2.2-SNAPSHOT@sha256:a8599b27219d9cb85b596fd90d173e370c3d53494630a98c00bee43f5c7bd8e6
    container_name: indexer
    env_file: .env
    links:
      - fcrepo:localhost
    volumes:
      - ./.hosts:/etc/hosts:Z
      - ./.esindex.json:/app/esindex.json:Z      

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./.elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    ports:
      - "${ES_PORT}:${ES_PORT}"

volumes:
  esdata:
    driver: local
